# Generated by Django 5.2.6 on 2025-11-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='body_material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Body Material'),
        ),
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='products',
            name='burner_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Burners'),
        ),
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(default='Black', max_length=50, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='products',
            name='dimensions_cm',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dimensions (W x H x D cm)'),
        ),
        migrations.AddField(
            model_name='products',
            name='grilling_area_sq_inch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grilling Area (e.g. sq. in / cm²)'),
        ),
        migrations.AddField(
            model_name='products',
            name='has_side_burner',
            field=models.BooleanField(default=False, verbose_name='Side Burner'),
        ),
        migrations.AddField(
            model_name='products',
            name='has_thermometer',
            field=models.BooleanField(default=False, verbose_name='Built-in Thermometer'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_portable',
            field=models.BooleanField(default=False, verbose_name='Portable'),
        ),
        migrations.AddField(
            model_name='products',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Power (kW/BTU)'),
        ),
        migrations.AddField(
            model_name='products',
            name='warranty_years',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Warranty (Years)'),
        ),
        migrations.AddField(
            model_name='products',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Weight (kg)'),
        ),
    ]
